// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"

// Slack is an autogenerated mock type for the Slack type
type Slack struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: ctx, channel, msg
func (_m *Slack) SendMessage(ctx context.Context, channel string, msg string) error {
	ret := _m.Called(ctx, channel, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, channel, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
